global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
    - job_name: 'node-resources'
      scrape_interval: 10s
      static_configs:
          - targets: ['exporter:9100']
rule_files:
  - 'alert.rules'
